In [ ]:
#Importing necessary libraries
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt   
import yfinance as yf 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler

In [ ]:
#Getting the data for a stock from the start date to the end date
start_date = '2010-01-01'
end_date = '2024-07-15'

stock_symbol = "GOOG"

data = yf.download(stock_symbol , start_date , end_date)

In [ ]:
print(data)

In [ ]:
#Add new index(0,1,2,...) instead of date column:
data.reset_index(inplace = True)

In [ ]:
data

In [ ]:
#We will be using the method of moving averages:
#Moving averages --> Calculate the value for the past 10 days and based on that value predict the value for the 11th day

#Calculating the moving average for 100 days and then plotting it:
mov_avg_100_days = data.Close.rolling(100).mean()

In [ ]:
#Plotting:
plt.figure(figsize=(15,15))
plt.plot(mov_avg_100_days , 'b')
plt.plot(data.Close , 'r')
plt.show()

In [ ]:
#Checking for null values:
data.isnull().sum()

In [ ]:
close_data = data[['Close']]

In [ ]:
close_data

In [ ]:
train_data , test_data = train_test_split(close_data , test_size=0.2, shuffle=False)

In [ ]:
print("Number of rows in the training data: " , train_data.shape[0])
print("Number of rows in the testing data: " , test_data.shape[0])

In [ ]:
train_data

In [ ]:
test_data

In [ ]:
#Normalizing the training data:
scaler = MinMaxScaler(feature_range=(0,1))

In [ ]:
train_data_scaled = scaler.fit_transform(train_data)

In [ ]:
#Now, applying the concept of moving averages on the scaled training data:
x = []
y = []

for i in range(100 , train_data_scaled.shape[0]):
    x.append(train_data_scaled[i-100 : i])
    y.append(train_data_scaled[i , 0])

#### EXPLAINATION OF WHAT THE LOOP ABOVE DOES. [taken from chatgpt]

# Initialize lists to hold sequences and targets
x = []
y = []

# Create sequences with a window size of 5
window_size = 5

# Loop through the data to create the input sequences and corresponding targets
for i in range(window_size, train_data_scaled.shape[0]):
    x.append(train_data_scaled[i-window_size:i])
    y.append(train_data_scaled[i])

# Convert lists to numpy arrays for better handling
x = np.array(x)
y = np.array(y)

# Print the resulting sequences and targets
print("x (input sequences):")
print(x)
print("\ny (targets):")
print(y)
Output:
The above code will produce the following output:

python
Copy code
x (input sequences):
[[0.1  0.15 0.2  0.25 0.3 ]
 [0.15 0.2  0.25 0.3  0.35]
 [0.2  0.25 0.3  0.35 0.4 ]
 [0.25 0.3  0.35 0.4  0.45]
 [0.3  0.35 0.4  0.45 0.5 ]
 [0.35 0.4  0.45 0.5  0.55]
 [0.4  0.45 0.5  0.55 0.6 ]
 [0.45 0.5  0.55 0.6  0.65]
 [0.5  0.55 0.6  0.65 0.7 ]
 [0.55 0.6  0.65 0.7  0.75]
 [0.6  0.65 0.7  0.75 0.8 ]
 [0.65 0.7  0.75 0.8  0.85]
 [0.7  0.75 0.8  0.85 0.9 ]
 [0.75 0.8  0.85 0.9  0.95]
 [0.8  0.85 0.9  0.95 1.  ]
 [0.85 0.9  0.95 1.   1.05]
 [0.9  0.95 1.   1.05 1.1 ]
 [0.95 1.   1.05 1.1  1.15]
 [1.   1.05 1.1  1.15 1.2 ]
 [1.05 1.1  1.15 1.2  1.25]
 [1.1  1.15 1.2  1.25 1.3 ]
 [1.15 1.2  1.25 1.3  1.35]
 [1.2  1.25 1.3  1.35 1.4 ]
 [1.25 1.3  1.35 1.4  1.45]
 [1.3  1.35 1.4  1.45 1.5 ]
 [1.35 1.4  1.45 1.5  1.55]
 [1.4  1.45 1.5  1.55 1.6 ]
 [1.45 1.5  1.55 1.6  1.65]
 [1.5  1.55 1.6  1.65 1.7 ]
 [1.55 1.6  1.65 1.7  1.75]
 [1.6  1.65 1.7  1.75 1.8 ]
 [1.65 1.7  1.75 1.8  1.85]
 [1.7  1.75 1.8  1.85 1.9 ]
 [1.75 1.8  1.85 1.9  1.95]
 [1.8  1.85 1.9  1.95 2.  ]
 [1.85 1.9  1.95 2.   2.05]
 [1.9  1.95 2.   2.05 2.1 ]
 [1.95 2.   2.05 2.1  2.15]
 [2.   2.05 2.1  2.15 2.2 ]
 [2.05 2.1  2.15 2.2  2.25]
 [2.1  2.15 2.2  2.25 2.3 ]
 [2.15 2.2  2.25 2.3  2.35]
 [2.2  2.25 2.3  2.35 2.4 ]
 [2.25 2.3  2.35 2.4  2.45]
 [2.3  2.35 2.4  2.45 2.5 ]]

y (targets):
[0.35 0.4  0.45 0.5  0.55 0.6  0.65 0.7  0.75 0.8  0.85 0.9  0.95 1.
 1.05 1.1  1.15 1.2  1.25 1.3  1.35 1.4  1.45 1.5  1.55 1.6  1.65 1.7
 1.75 1.8  1.85 1.9  1.95 2.   2.05 2.1  2.15 2.2  2.25 2.3  2.35 2.4
 2.45 2.5 ]



In this example, each element in x is a sequence of 5 values from train_data_scaled, and each corresponding element in y is the value immediately following the sequence. This setup is used to train models for time series forecasting, where the model learns to predict the next value in the sequence based on the previous values.

In [ ]:
print("X is: " , x)
print("\nY is: " , y)

In [ ]:
#CREATING THE MODEL FROM HERE ON:

In [ ]:
from keras.layers import Dense , Dropout , LSTM    
from keras.models import Sequential